apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8s-deployment
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-cdk8s
      environment: prod
  template:
    metadata:
      labels:
        app: hello-cdk8s
        environment: prod
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.7
          name: hello-kubernetes
          ports:
            - containerPort: 8080
