apiVersion: v1
kind: Service
metadata:
  name: next-app-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: next-app 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app 
  template:
    metadata:
      labels:
        app: next-app 
    spec:
      containers:
        - image: 455595963207.dkr.ecr.ap-southeast-1.amazonaws.com/next-app:latest 
          name: next-app 
          ports:
            - containerPort: 3000 
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 500m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: next-app-hpa 
spec:
  maxReplicas: 1000
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 5
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: next-app-deployment 
