apiVersion: v1
kind: Service
metadata:
  name: notebook 
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: notebook 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notebook 
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - image: 215970698483.dkr.ecr.ap-southeast-1.amazonaws.com/jupyter/datascience-notebook:latest 
          name: notebook
          ports:
            - containerPort: 8888
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 500m