apiVersion: v1
kind: Service
metadata:
  name: polly-image-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:315305460736:certificate/1b66b634-0e5a-4371-9517-67b8d2863cf5
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
    - port: 443
      targetPort: 3000
      name: https
  selector:
    app: polly-image-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polly-image-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polly-image-app
  template:
    metadata:
      labels:
        app: polly-image-app
    spec:
      containers:
        - image: 315305460736.dkr.ecr.us-east-1.amazonaws.com/polly-image-app
          name: polly-image-app
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: polly-image-app-hpa
spec:
  maxReplicas: 1000
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 5
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: polly-image-app-deployment
