apiVersion: v1
kind: Service
metadata:
  name: next-diffusion-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:243323833040:certificate/91a45543-827d-4668-8f4a-b7cd1024e096
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
    - port: 443
      targetPort: 3000
      name: https
  selector:
    app: next-diffusion-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-diffusion-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-diffusion-app
      environment: dev
  template:
    metadata:
      labels:
        app: next-diffusion-app
        environment: dev
    spec:
      containers:
        - image: 243323833040.dkr.ecr.ap-southeast-1.amazonaws.com/next-diffusion-app
          name: next-diffusion-app
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m
