apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  namespace: default
  name: dev-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: dev-role-binding
  namespace: default 
subjects: 
- kind: User 
  name: developer
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
